Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: LAMP-
    TemplateConfigs:
      - Name: 选择ECS实例（Linux）
        Url: 'ros_templates/template-select-ecs.yaml'
      - Name: 新建ECS实例
        Url: 'ros_templates/template-create-ecs.yaml'
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: LAMP 是一种经典的开源软件堆栈，用于构建动态网站和 Web 应用程序。LAMP 代表 Linux、Apache、MySQL（或 MariaDB）和 PHP。这一组合在开发和部署 Web 解决方案时非常流行，并具有高效、可靠和可扩展的特点。
    Image: 'resources/icons/service_logo.png'
